config/routes.rb
Rails.application.routes.draw do
  get 'reviews' => 'reviews#index'
  post 'reviews' => 'reviews#create'

  get 'tags' => 'keywords#index'
  get 'categories' => 'categories#index'

  get 'tickets/:id/apply' => 'tickets#apply_list'
  get 'tickets/my_list' => 'tickets#my_list'
  post 'tickets/:id/stock' => 'tickets#stock'
  post 'tickets/:id/apply' => 'tickets#apply'
  patch 'tickets/:id/select_teacher' => 'tickets#select_teacher'
  put 'tickets/:id/select_teacher' => 'tickets#select_teacher'
  post'tickets/:id/select_teacher' => 'tickets#select_teacher'
  patch 'tickets/:id/read' => 'tickets#read'
  put 'tickets/:id/read' => 'tickets#read'
  post 'tickets/:id/read' => 'tickets#read'
  delete 'tickets/:id/stock' => 'tickets#unstock'
  resources :tickets

  get 'users/:id' => 'users#show'
  patch 'users/:id' => 'users#update'
  put 'users/:id' => 'users#update'
  post 'users/:id' => 'users#update'
  post 'users/:id/select_tags/' => 'users#select_tags'
  delete 'users/:id' => 'users#destroy'
  devise_for :users, :skip => [:sessions], :controllers => { registrations: 'registrations' }
  as :user do
    post 'login' => 'sessions#create', :as => :user_session
    delete 'logout' => 'authentication_tokens#destroy', :as => :destroy_user_session
  end
  get 'hello' => 'hello#index'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :bought_user, class_name: 'User'
  has_many :stock_tickets, dependent: :delete_all
  has_many :keywords_tickets, dependent: :delete_all
  has_many :keywords, through: :keywords_tickets
  has_many :ticket_candidates, dependent: :delete_all
  has_many :candidates, through: :ticket_candidates
  has_many :matching_tickets, dependent: :delete_all
  has_one :review

  scope :user, ->(user_id) { where(user_id: user_id) }
  scope :bought_user, ->(bought_user_id) { where(bought_user_id: bought_user_id) }
  scope :bought, -> { where(bought: true) }
  scope :no_bought, -> { where(bought: false) }
  scope :beginner, -> { where(beginner: true) }
  scope :no_beginner, -> { where(beginner: false) }
  scope :online, -> { where('skype OR hangouts') }
  scope :offline, -> { where.not(offline_place: nil) }
  scope :ticket_ids, ->(ticket_ids) { where(id: ticket_ids) }
  scope :joins_stock_tickets_where_user, ->(user_id) { joins(:stock_tickets).where(stock_tickets: { user_id: user_id }) }
  scope :joins_users_where_sex, ->(sex) { joins(:user).where(users: { sex: sex }) }
  scope :order_limit_offset, ->(order, limit, offset) { order(order).limit(limit).offset(offset) }
  scope :search, ->(query) { where("tickets.title LIKE '%#{query}%' OR tickets.body LIKE '%#{query}%'") }
  scope :search_with_in, ->(keyword_ticket_ids, query) { where("tickets.id IN (#{keyword_ticket_ids}) OR tickets.title LIKE '%#{query}%' OR tickets.body LIKE '%#{query}%'") }
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  load_and_authorize_resource
  skip_load_and_authorize_resource only: [:index, :apply_list, :show, :stock, :apply, :read, :unstock]
  before_action :set_ticket, only: [:apply_list, :show, :edit, :update, :apply, :read, :destroy]
  before_action :set_default_if_no_params, only: [:index, :my_list]

  DEFAULT_SORT = 'create'
  DEFAULT_SORT_STOCK = 'stock'
  DEFAULT_ORDER = 'd'
  DEFAULT_LIMIT = 10
  DEFAULT_OFFSET = 0
  DEFAULT_FILTER = 'all'

  # GET /tickets
  # GET /tickets.json
  def index
    # filterがteachedまたはlearnedまたはstockの時はuser_idが必要
    if ['matching', 'teached', 'learned', 'stock'].include?(params[:filter]) && params[:user_id].blank?
      render json: { message: 'ERROR: need user_id parameter!' }, status: 500
    end

    query = Ticket.includes(:user, :bought_user, :keywords, :keywords_tickets).order_limit_offset(make_order_query, params[:limit], params[:offset])

    # 性別でフィルタリング
    query = query.joins_users_where_sex(params[:sex]) if params[:sex].present?

    # タグでフィルタリング
    if params[:tag_id]
      ticket_ids = KeywordsTicket.select(:ticket_id).where(keyword_id: params[:tag_id]).map(&:ticket_id)
      query = query.ticket_ids(ticket_ids)
    end

    # クエリで検索
    if params[:q].present?
      keyword_ticket_ids = KeywordsTicket.select(:ticket_id).joins(:keyword).where("keywords.name LIKE '%#{params[:q]}%'").map(&:ticket_id).uniq
      query = keyword_ticket_ids.blank? ? query.search(params[:q]) : query.search_with_in(keyword_ticket_ids.join(','), params[:q])
    end

    # 場所でフィルタリング
    query = query.send(params[:place]) if params[:place].present?

    # スキルでフィルタリング
    if params[:beginner].present?
      case params[:beginner]
      when '0' then
        query = query.no_beginner
      when '1' then
        query = query.beginner
      end
    end

    case params[:filter]
    when 'matching' then
      matching_tickets_ids = MatchingTicket.select(:ticket_id).where(user_id: params[:user_id]).map(&:ticket_id)
      @tickets = query.no_bought.ticket_ids(matching_tickets_ids)

      render "matching", :formats => [:json], :handlers => [:jbuilder]
    when 'no_bought' then
      query = query.no_bought
      query = query.user(params[:user_id]) if params[:user_id].present?
    when 'teached' then
      query = query.bought_user(params[:user_id])
    when 'learned' then
      query = query.user(params[:user_id]).bought
    when 'stock' then
      query = query.no_bought.joins_stock_tickets_where_user(params[:user_id])
    end

    @tickets = query
  end

  def apply_list
    @ticket_candidates = @ticket.ticket_candidates.order('id desc')
  end

  def my_list
    @tickets = Ticket.includes(:user, :bought_user).accessible_by(current_ability).no_bought.order_limit_offset(make_order_query, params[:limit], params[:offset])
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params.merge(user: current_user))

    respond_to do |format|
      if @ticket.save
        # create keywords_tickets
        keywords = params[:ticket][:tags].map { |keyword_id| Hash[*['keyword_id', 'ticket_id'].zip([keyword_id, @ticket.id]).flatten] }
        KeywordsTicket.create(keywords)

        # enqueue matching job
        #MailTestJob.set(wait: 10.second).perform_later
        #MatchingUserJob.set(wait: 10.second).perform_later(@ticket)

        matching_user_ids = MatchingTicket.search_matching_user(@ticket)
        Rails.logger.debug("matching_user_ids: #{matching_user_ids}")
        MatchingTicket.create(make_matching_ticket(matching_user_ids, @ticket.id))
        Rails.logger.debug("matching_user created.")

        # お互いに通知する
        MatchingMailer.for_matching_user(matching_user_ids, @ticket).deliver_now
        #MatchingMailer.for_creating_user(matching_user_ids, @ticket).deliver_now

        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /tickets/1/stock.json
  def stock
    @stock_ticket = StockTicket.new(ticket_id: params[:id], user_id: current_user.id)

    if @stock_ticket.save
      render json: { message: 'Ticket was successfully stocked.' }
    else
      render json: @stock_ticket.errors, status: :unprocessable_entity
    end
  end

  # POST /tickets/1/apply.json
  def apply
    ticket_candidate = TicketCandidate.new(comment: params[:comment], ticket_id: params[:id], user_id: current_user.id)

    if @ticket.user_id != current_user.id && ticket_candidate.save
      render json: { message: 'Ticket was successfully applied.' }
    else
      render json: @stock_ticket.errors, status: :unprocessable_entity
    end
  end

  # PATCH /tickets/1/select_teacher.json
  def select_teacher
    unless @ticket.bought
      @ticket.update_attributes(bought: true, bought_user_id: params[:teacher_id])
      render json: { message: 'Ticket was successfully bought.' }
    else
      render json: @ticket.errors, status: :unprocessable_entity
    end
  end

  # PATCH /tickets/1/read.json
  def read
    unless @ticket.user_id == current_user.id
      matching_ticket = @ticket.matching_tickets.find_by(user_id: current_user.id)
      unless matching_ticket.read_flag
        matching_ticket.update_attribute(:read_flag, true)
        render json: { message: 'Ticket was successfully read.' }
      end
    else
    render json: @ticket.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        # update keywords_tickets
        if params[:ticket][:tags].present?
          KeywordsTicket.where(ticket_id: @ticket.id).each(&:destroy)
          keywords = params[:ticket][:tags].map { |keyword_id| Hash[*['keyword_id', 'ticket_id'].zip([keyword_id, @ticket.id]).flatten] }
          KeywordsTicket.create(keywords)
        end

        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1/stock.json
  def unstock
    StockTicket.find_by(ticket_id: params[:id], user_id: current_user.id).destroy
    render json: { message: 'Ticket was successfully unstocked.' }
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { render json: { message: 'Ticket was successfully destroyed.' } }
    end
  end

  private
    def make_matching_ticket(user_ids, ticket_id)
      user_ids.map { |user_id| Hash[*['user_id', 'ticket_id'].zip([user_id, ticket_id]).flatten] }
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:title, :body, :time, :price, :skype, :hangouts, :offline_place, :bought, :user_id, :bought_user_id, :beginner)
    end

    def set_default_if_no_params
      params[:sort] ||= (params[:filter] == 'stock') ? DEFAULT_SORT_STOCK : DEFAULT_SORT
      params[:order] ||= DEFAULT_ORDER
      params[:limit] ||= DEFAULT_LIMIT
      params[:offset] ||= DEFAULT_OFFSET
      params[:filter] ||= DEFAULT_FILTER
    end

    def make_order_query
      case params[:order]
      when 'd' then
        order_query = ' desc'
      when 'a' then
        order_query = ' asc'
      end

      case params[:sort]
      when 'create' then
        'tickets.id' + order_query
      when 'popular' then
        popular_ticket_ids_asc = StockTicket.group(:ticket_id).order('count_ticket_id asc, ticket_id asc').count(:ticket_id).keys
        ActiveRecord::Base.send(:sanitize_sql_array, ["field(id,?) desc", popular_ticket_ids_asc])
      when 'noticed' then
        noticed_ticket_ids_asc = TicketCandidate.group(:ticket_id).order('count_ticket_id asc, ticket_id asc').count(:ticket_id).keys
        ActiveRecord::Base.send(:sanitize_sql_array, ["field(id,?) desc", noticed_ticket_ids_asc])
      when 'stock' then
        'stock_tickets.id' + order_query
      else
        params[:sort] + order_query + ', tickets.id desc'
      end
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :bought %><br>
    <%= f.check_box :bought %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :bought_user_id %><br>
    <%= f.text_field :bought_user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Time</th>
      <th>Price</th>
      <th>Place</th>
      <th>Bought</th>
      <th>User</th>
      <th>BoughtUser</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.title %></td>
        <td><%= ticket.body %></td>
        <td><%= ticket.time %></td>
        <td><%= ticket.price %></td>
        <td><%= ticket.place %></td>
        <td><%= ticket.bought %></td>
        <td><%= ticket.user %></td>
        <td><%= ticket.bought_user %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ticket.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @ticket.body %>
</p>

<p>
  <strong>Time:</strong>
  <%= @ticket.time %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>

<p>
  <strong>Place:</strong>
  <%= @ticket.place %>
</p>

<p>
  <strong>Bought:</strong>
  <%= @ticket.bought %>
</p>

<p>
  <strong>User:</strong>
  <%= @ticket.user %>
</p>

<p>
  <strong>BoughtUser:</strong>
  <%= @ticket.bought_user %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>